WIP

diff --git a/scripts/check_multiple_working b/scripts/check_multiple_working
--- a/scripts/check_multiple_working
+++ b/scripts/check_multiple_working
@@ -1,6 +1,7 @@
 ############################################################################
 #
 # Copyright (c) 2011 - dsixda (dislam@rocketmail.com)
+# Copyright (c) 2014 - JustArchi (JustArchi@JustArchi.net)
 #
 # Android Kitchen is 100% free.  This script file is intended for personal
 # and/or educational use only.  It may not be duplicated for monetary
@@ -8,13 +9,9 @@
 #
 ############################################################################
 
-
-num_working=`ls | grep -c "^WORKING_"`
-if [ $num_working -gt 1 ]
-then
-  echo
-  echo "Error: You have more than one working folder created"
-  exit 1
+if [ `ls | grep -c "^WORKING_"` -gt 1 ]; then
+	echo "Error: You have more than one working folder created!"
+	exit 1
 fi 
 
 exit 0
